package internal

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const marker = "# Generated by cpm (Claude Profile Manager)"

// subcommands that pass through unmodified to claude.
const subcommands = "mcp|auth|doctor|install|setup-token|update|upgrade|agents|auto-mode|plugin|plugins"

// WrapperFiles describes the file(s) GenerateWrapper produces.
// Unix: Main + MainContent. Sidecar empty.
// Windows: Main = "claude-<name>.cmd", Sidecar = "claude-<name>.ps1".
type WrapperFiles struct {
	Main           string // base filename (no directory)
	MainContent    string
	Sidecar        string // base filename; empty if no sidecar
	SidecarContent string
	Mode           uint32 // file mode (e.g. 0o755 on Unix; ignored on Windows)
}

// InstallWrapper writes the wrapper file(s) into binDir.
// Returns the path of the main file (for the caller's log output).
func InstallWrapper(binDir string, files WrapperFiles) (string, error) {
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		return "", err
	}

	mainPath := filepath.Join(binDir, files.Main)
	if err := writeIfChanged(mainPath, files.MainContent, files.Mode); err != nil {
		return "", err
	}

	if files.Sidecar != "" {
		sidecarPath := filepath.Join(binDir, files.Sidecar)
		if err := writeIfChanged(sidecarPath, files.SidecarContent, files.Mode); err != nil {
			return "", err
		}
	}

	return mainPath, nil
}

func writeIfChanged(path, content string, mode uint32) error {
	if existing, err := os.ReadFile(path); err == nil && string(existing) == content {
		return nil
	}
	if err := os.WriteFile(path, []byte(content), os.FileMode(mode)); err != nil {
		return err
	}
	fmt.Printf("  installed %s\n", path)
	return nil
}

// CleanupStaleScripts walks binDir and removes any file containing the
// cpm-generated marker that does not belong to an active profile.
// activeProfileNames maps profile names (e.g. "personal") to true.
func CleanupStaleScripts(binDir string, activeProfileNames map[string]bool) {
	entries, err := os.ReadDir(binDir)
	if err != nil {
		return
	}

	activeFiles := make(map[string]bool, len(activeProfileNames)*2)
	for prof := range activeProfileNames {
		for _, fn := range wrapperFilenames(prof) {
			activeFiles[fn] = true
		}
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		// Only consider files named like a profile wrapper. Skips cpm.exe
		// itself (the Go binary embeds the marker constant in .rodata) and
		// any unrelated scripts users may have placed in bin_dir.
		if !strings.HasPrefix(name, "claude-") {
			continue
		}
		if activeFiles[name] {
			continue
		}
		path := filepath.Join(binDir, name)
		content, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		if !strings.Contains(string(content), marker) {
			continue
		}
		if err := os.Remove(path); err != nil {
			fmt.Printf("  could not remove stale script %s: %v\n", path, err)
			continue
		}
		fmt.Printf("  removed stale script %s\n", path)
	}
}
