//go:build !windows

package internal

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateWrapperBasic(t *testing.T) {
	profile := &Profile{
		Description: "Personal account",
	}

	files := GenerateWrapper("personal", "/home/user/.claude-profiles/personal", profile)
	out := files.MainContent

	if files.Main != "claude-personal" {
		t.Errorf("Main = %q, want claude-personal", files.Main)
	}
	if files.Sidecar != "" {
		t.Errorf("Sidecar = %q, want empty on Unix", files.Sidecar)
	}
	if files.Mode != 0o755 {
		t.Errorf("Mode = %o, want 0755", files.Mode)
	}

	mustContain := []string{
		"#!/usr/bin/env bash",
		"Generated by cpm",
		"Profile: personal",
		`CLAUDE_CONFIG_DIR="/home/user/.claude-profiles/personal"`,
		`CLAUDE_PROFILE="personal"`,
		"exec claude",
	}

	for _, s := range mustContain {
		if !strings.Contains(out, s) {
			t.Errorf("wrapper missing %q", s)
		}
	}
}

func TestGenerateWrapperWithModel(t *testing.T) {
	profile := &Profile{
		Description: "Work",
		Model:       "sonnet",
	}

	out := GenerateWrapper("work", "/profiles/work", profile).MainContent

	if !strings.Contains(out, "has_model=false") {
		t.Error("wrapper should contain model detection logic")
	}
	if !strings.Contains(out, "--model sonnet") {
		t.Error("wrapper should contain --model sonnet")
	}
}

func TestGenerateWrapperWithAddDirs(t *testing.T) {
	home, _ := os.UserHomeDir()
	profile := &Profile{
		Description: "Work",
		AddDirs:     []string{"~/Work/company"},
	}

	out := GenerateWrapper("work", "/profiles/work", profile).MainContent

	expected := filepath.Join(home, "Work/company")
	if !strings.Contains(out, "--add-dir \""+expected+"\"") {
		t.Errorf("wrapper should contain --add-dir for %s", expected)
	}
}

func TestGenerateWrapperWithEnv(t *testing.T) {
	profile := &Profile{
		Description: "Vertex",
		Env: map[string]string{
			"CLAUDE_CODE_USE_VERTEX": "1",
			"CLOUD_ML_REGION":        "europe-west1",
		},
	}

	out := GenerateWrapper("vertex", "/profiles/vertex", profile).MainContent

	if !strings.Contains(out, `CLAUDE_CODE_USE_VERTEX="1"`) {
		t.Error("wrapper missing CLAUDE_CODE_USE_VERTEX")
	}
	if !strings.Contains(out, `CLOUD_ML_REGION="europe-west1"`) {
		t.Error("wrapper missing CLOUD_ML_REGION")
	}
}

func TestGenerateWrapperSubcommandBypass(t *testing.T) {
	profile := &Profile{Description: "Test"}
	out := GenerateWrapper("test", "/profiles/test", profile).MainContent

	for _, sub := range []string{"mcp", "auth", "doctor"} {
		if !strings.Contains(out, sub) {
			t.Errorf("wrapper should handle subcommand %q", sub)
		}
	}
}
